[aws]
disabled = true
format = "on [$symbol$profile]($style) "
style = "bold blue"
symbol = "ğŸ…° "

[battery]
full_symbol = "ğŸ”‹ "
discharging_symbol = "âš¡ï¸ "
charging_symbol = "ğŸ”Œ "
empty_symbol = "ğŸª« "
unknown_symbol = "ğŸ’€ "

[[battery.display]]  # "bold red" style when capacity is between 0% and 15%
threshold = 15
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 15% and 30%
threshold = 30
style = "bold yellow"

[directory]
fish_style_pwd_dir_length = 1

[git_status]
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
staged = '[++\($count\)](green)'

[kubernetes]
format = "on [â›µ $context \\($namespace\\)](dimmed green) "
disabled = false
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"

[memory_usage]  # warn when less than 80% free memory available
disabled = false
threshold = 80
